create database grocery_management_proj;
use grocery_management_proj;
-- 1.supplier table
CREATE TABLE IF NOT EXISTS supplier ( 
    sup_id TINYINT PRIMARY KEY, 
    sup_name VARCHAR(255), 
    address TEXT 
); 
 -- 2. Categories Table 
CREATE TABLE IF NOT EXISTS categories ( 
    cat_id TINYINT PRIMARY KEY, 
    cat_name VARCHAR(255) 
); 
 -- 3. Employees Table 
CREATE TABLE IF NOT EXISTS employees ( 
    emp_id TINYINT PRIMARY KEY, 
    emp_name VARCHAR(255), 
    hire_date VARCHAR(255) 
); 
 -- 4. Customers Table 
CREATE TABLE IF NOT EXISTS customers ( 
    cust_id SMALLINT PRIMARY KEY, 
    cust_name VARCHAR(255), 
    address TEXT 
); 
 -- 5. Products Table 
CREATE TABLE IF NOT EXISTS products ( 
    prod_id TINYINT PRIMARY KEY, 
    prod_name VARCHAR(255), 
    sup_id TINYINT, 
    cat_id TINYINT, 
    price DECIMAL(10,2), 
    FOREIGN KEY (sup_id) REFERENCES supplier(sup_id) 
        ON UPDATE CASCADE ON DELETE CASCADE, 
    FOREIGN KEY (cat_id) REFERENCES categories(cat_id) 
        ON UPDATE CASCADE ON DELETE CASCADE 
); 
 -- 6. Orders Table 
CREATE TABLE IF NOT EXISTS orders ( 
    ord_id SMALLINT PRIMARY KEY, 
    cust_id SMALLINT, 
    emp_id TINYINT, 
    order_date VARCHAR(255), 
    FOREIGN KEY (cust_id) REFERENCES customers(cust_id) 
        ON UPDATE CASCADE ON DELETE CASCADE, 
    FOREIGN KEY (emp_id) REFERENCES employees(emp_id) 
        ON UPDATE CASCADE ON DELETE CASCADE 
); 
-- 7. Order_Details Table 
CREATE TABLE IF NOT EXISTS order_details ( 
ord_detID SMALLINT AUTO_INCREMENT PRIMARY KEY, 
ord_id SMALLINT, 
prod_id TINYINT, 
quantity TINYINT, 
each_price DECIMAL(10,2), 
total_price DECIMAL(10,2), 
FOREIGN KEY (ord_id) REFERENCES orders(ord_id) 
ON UPDATE CASCADE ON DELETE CASCADE, 
FOREIGN KEY (prod_id) REFERENCES products(prod_id) 
ON UPDATE CASCADE ON DELETE CASCADE 
);

-- QUERIES;

-- Customer Insights
 -- ● How many unique customers have placed orders?
select count(distinct cust_id) as unique_customers_count
from orders;

 
 -- ● Which customers have placed the highest number of orders? 
select cust_id, count(ord_id) as orders_no
from orders
group by cust_id
having orders_no = (
    select max(order_count)
    from (
        select cust_id, count(ord_id) as order_count
        from orders
        group by cust_id) temp);

        
-- ● What is the total and average purchase value per customer? 

select o.cust_id,
       sum(od.total_price) as total_purchase,
       avg(od.total_price) as avg_purchase
from orders o
join order_details od
  on o.ord_id = od.ord_id
group by o.cust_id;


-- ● Who are the top 5 customers by total purchase amount? 

select o.cust_id,sum(od.total_price) as total_purchase
from orders o
join order_details od
on o.ord_id=od.ord_id
group by o.cust_id
order by total_purchase desc
limit 5;

-- 2. Product Performance 
-- Evaluate how well products are performing in terms of sales and revenue. 
-- ● How many products exist in each category?
select c.cat_name,
       count(p.prod_id) as product_count
from categories c
join products p
  on c.cat_id = p.cat_id
group by c.cat_name;


-- What is the average price of products by category? 
select c.cat_name,
       avg(p.price) as avg_price
from categories c
join products p
  on c.cat_id = p.cat_id
group by c.cat_name;


-- ● Which products have the highest total sales volume (by quantity)? 
select p.prod_name,sum(o.quantity) as total_sales_volume
from order_details o
join products p
on o.prod_id=p.prod_id
group by p.prod_name
order by total_sales_volume desc;

-- ● What is the total revenue generated by each product? 
select p.prod_name,
       sum(od.total_price) as total_revenue
from products p
join order_details od
on p.prod_id = od.prod_id
group by p.prod_name;


-- ● How do product sales vary by category and supplier? 
select c.cat_name,
       s.sup_id,
       s.sup_name,
       sum(od.quantity) as product_sales
from supplier s
join products p
  on s.sup_id = p.sup_id
join categories c
  on p.cat_id = c.cat_id
join order_details od
  on p.prod_id = od.prod_id
group by c.cat_name, s.sup_id, s.sup_name
order by c.cat_name, product_sales desc;



-- 3. Sales and Order Trends 
-- Analyze business performance through orders and revenue over time. 
-- ● How many orders have been placed in total?

select count(distinct(ord_id)) as total_orders_placed
from order_details;

-- ● What is the average value per order?
select avg(total_value) as avg_value_per_order
from (select sum(total_price) as total_value
from order_details
group by ord_id) as temp;

-- ● On which dates were the most orders placed? 
select o.order_date,count(distinct(d.ord_id)) as count_of_orders
from orders o
join order_details d
on o.ord_id=d.ord_id
group by order_date
order by count_of_orders desc;

-- ● What are the monthly trends in order volume and revenue? 
SELECT 
    YEAR(STR_TO_DATE(o.order_date, '%m/%d/%Y')) AS year,
    MONTH(STR_TO_DATE(o.order_date, '%m/%d/%Y')) AS month,
    COUNT(DISTINCT o.ord_id) AS total_orders,
    SUM(d.total_price) AS total_revenue
FROM orders o
JOIN order_details d
    ON o.ord_id = d.ord_id
GROUP BY 
    YEAR(STR_TO_DATE(o.order_date, '%m/%d/%Y')),
    MONTH(STR_TO_DATE(o.order_date, '%m/%d/%Y'))
ORDER BY year, month;

-- ● How do order patterns vary across weekdays and weekends? 

select case 
when dayofweek(order_date) in (1,7) then 'Weekend'
else 'Weekday'
end as day_type,count(distinct ord_id) as total_orders
from orders
group by day_type;

-- 4. Supplier Contribution 
-- Identify the most active and profitable suppliers. 
-- ● How many suppliers are there in the database?
select count(distinct(sup_id)) as supplier_count
from supplier;

-- ● Which supplier provides the most products? 
select s.sup_name,count(distinct(p.prod_id)) as no_prod 
from supplier s
join products p
on s.sup_id=p.sup_id
group by s.sup_name
order by no_prod desc
limit 1;

-- ● What is the average price of products from each supplier? 
select s.sup_name,avg(p.price) as avg_price
from products p
join supplier s
on p.sup_id=s.sup_id
group by s.sup_name;

-- ● Which suppliers contribute the most to total product sales (by revenue)? 
select s.sup_name,sum(p.price * od.quantity) as revenue
from supplier s
join products p
on s.sup_id=p.sup_id
join order_details od
on p.prod_id=od.prod_id
group by s.sup_name
order by revenue desc;

-- 5. Employee Performance 
-- Assess how employees are handling and influencing sales. 
-- ● How many employees have processed orders?
select count(distinct o.emp_id) as employees_processed_orders
from orders o;

-- ● Which employees have handled the most orders? 
select e.emp_name,count(o.ord_id) as orders_count
from employees e
inner join orders o
on e.emp_id=o.emp_id
group by e.emp_name;

-- ● What is the total sales value processed by each employee? 
SELECT e.emp_id,sum(od.total_price * od.quantity) as total_sales
from employees e
join orders o
on e.emp_id=o.emp_id
join order_details od
on o.ord_id=od.ord_id
group by e.emp_id;

-- ● Which suppliers contribute the most to total product sales (by revenue)? 
select s.sup_id,
sum(od.total_price * od.quantity) as product_sales
from supplier s
join products p
on s.sup_id=p.sup_id
join order_details od
on p.prod_id=od.prod_id
group by s.sup_id
order by product_sales desc;

-- 6. Order Details Deep Dive 
-- Explore item-level sales patterns and pricing behavior. 
-- ● What is the relationship between quantity ordered and total price? 
select quantity,avg(total_price) as avg_price,sum(total_price) as sum_price
from order_details
group by quantity;

-- ● What is the average quantity ordered per product? 
select prod_id,avg(quantity) as avg_quantity
from order_details
group by prod_id;

-- ● How does the unit price vary across products and orders? 
select 
    p.prod_name,
    avg(od.each_price) as avg_unit_price,
    min(od.each_price) as min_unit_price,
    max(od.each_price) as max_unit_price
from order_details od
join products p
on od.prod_id = p.prod_id
group by p.prod_name;




